name: Build/release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup package mirrors
        run: |
          npm config set registry https://registry.npmmirror.com
          yarn config set registry https://registry.npmmirror.com
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          SASS_BINARY_SITE: https://npmmirror.com/mirrors/node-sass/

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        if: startsWith(matrix.os, 'ubuntu')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

      - name: Test Snapcraft
        if: startsWith(matrix.os, 'ubuntu')
        run: snapcraft --help

      - name: Build/release Electron app
        uses: motrixapp/action-electron-builder@v2
        with:
          build_script_name: 'build:github'
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: ${{ vars.skip_publish != 'true' }}
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
          TEAM_ID: ${{ secrets.team_id }}
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.apple_app_specific_password }}
